config/routes.rb
Rails.application.routes.draw do
  resources :references
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :blogs do
    resources :comments
  end
  resources :skills
  resources :projects

  root 'skills#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :projects
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
    @references = Reference.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @projects = Project.where(skills_id: params[:id])
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:skill, :rating, :project_id, :description)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for(skill) do |f| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill %>
    <%= f.text_field :skill %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
       <div class="col s12 m6">
         <% @skills.each do |skill| %>
         <div class="card blue-grey darken-1">
           <div class="card-content white-text">
             <span class="card-title"><%= skill.skill %></span>
             <p><%= skill.description %></p>
           </div>
           <div class="card-action">
             <a href="#">Rating: <%= skill.rating %></a>
             <%= link_to 'Projects', skill %>
           </div>
         </div>
         <% end %>
       </div>
       <div class="col s12 m6">
         <h4>About Kiburei,</h4>
         <p>I am lucky to be fullstack software engineer and bachelors degree holder in Computer Technology. I like to think that computers hold the power to
         make the world a better place. I am actively particapting towards this by putting in work and this is why you are probably here. So we can change things together \o/.
         Do have a look at some of my past, current and ongoing projects. Other than computers I love the outdoors</p>
         <div class="references">
           <h5>References</h5>
           <%= link_to 'Add Reference', new_reference_path, class: 'btn', id: 'new_ref', remote: true  %>
           <div id="user_refs">
             <% if @references.any? %>
              <%= render 'references/reference' %>
             <% else %>
              <p>People dont like you</p>
             <% end %>
           </div>
        </div>
       </div>
    </div>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @skill.skill %></h2>

<% @projects.each do |project| %>
  <div class="card">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= project.name %></span>
        <p><%= project.description %></p>
      </div>
      <div class="card-action">
        <a href="<%= project.url %>"> Live Demo </a>
      </div>
    </div>
  </div>
<% end %>
<% if current_user.admin? %>
  <%= link_to 'Add Project', new_project_path, class: 'btn' %>
<% end %>
<%= link_to 'Back', skills_path, class: 'btn blue' %>