config/routes.rb
Rails.application.routes.draw do
  resources :references
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :blogs do
    resources :comments
  end
  resources :skills
  resources :projects

  root 'skills#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @references = Reference.all
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:name, :message)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for @reference, remote: true do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/_reference.html.erb
<% @references.each do |reference|%>
  <p><%= reference.name %> -- <%= reference.message %></p>
<% end %>

app/views/references/create.js.erb
$('#new_reference').remove();
$('#new_ref').show();
$('#user_refs').append('<%= j render @reference %>')

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.name %></td>
        <td><%= reference.message %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/new.js.erb
$('#new_ref').hide().after('<%= j render "form" %>');

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reference.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @reference.message %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>